#%RAML 1.0 Trait

queryParameters:
  customerId:
    description: Customer Identify
    type: integer

  contractId?:
    description: Contract Identify
    type: integer

  invoiceNumber?:
    description: invoice Number
    type: integer

  invoiceDateInit?:
    description: Invoice Date
    type: date-only

  invoiceDateEnd?:
    description: Invoice Date
    type: date-only